name: Renovate

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: Renovate log level
        default: info

concurrency:
  group: renovate
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run Renovate
        uses: renovatebot/github-action@v46.2.4
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
